// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmxffbltzwovqlsafcid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtteGZmYmx0endvdnFsc2FmY2lkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NzEzODQsImV4cCI6MjA3MjE0NzM4NH0.KSjbx4tsfcv1AASr7tmdrF5z6OxprYrDYEEgfT7K6Jo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});